# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

register_gdal_cpp <- function() {
    .Call(`_gdalwindow_register_gdal_cpp`)
}

raster_io_gdal_cpp <- function(dsn, window, band, resample) {
    .Call(`_gdalwindow_raster_io_gdal_cpp`, dsn, window, band, resample)
}

